### ISSUE TITLE
good reason for UTC (rather than local) timestamp?

### ISSUE THREAD

**Issue by aghitza** [alexjurkiewicz/acts#17]
I'm assuming having the archive names contain the timestamp relative to UTC time rather than local time was a design decision.  I find the behavior slightly disorienting (my local time is 10 hours ahead of UTC, so typically even the date is off).  Wouldn't local time be more generally useful?

**Comment by alexjurkiewicz** [comment]
Yeah, it was a deliberate decision. In commercial settings, I think system
infrastructure should assume UTC. There's some more background on the topic
here:
http://serverfault.com/questions/191331/should-servers-have-their-timezone-set-to-gmt-utc

But I do accept not everyone runs their personal infrastructure in such a
way :-)

If you're interested, I would accept a patch to change acts behaviour. The
patch would add an option (disabled by default) to use system local time
rather than UTC.

**Comment by aghitza** [comment]
OK, I've taken a shot at it.
