### ISSUE TITLE
Directory's name containing spaces

### ISSUE THREAD

**Issue by brunoqc** [alexjurkiewicz/acts#6]
Is it possible to backup a directory that contain a space in its name?

I tried escaping it like `directory\ name` but acts didn't like it.

acts-1.0
tarsnap 1.0.35
cygwin

**Comment by alexjurkiewicz** [comment]
Sorry, unfortunately there's no easy solution, due to the simple
(primitive) way acts reads its configuration file.

I don't think directories with spaces is a common use case either, so
complicating the code to support it is off the table until more of the user
base ask for it.

As a workaround, I'd suggest creating a symlink without spaces to the
directory you want to back up. This will complicate your restores somewhat,
of course.

**Comment by brunoqc** [comment]
> As a workaround, I'd suggest creating a symlink without spaces to the
directory you want to back up.

It seems tarsnap doesn't follow symlink by default and I can't use `tarsnap="tarsnap -L`
```
$ ./acts
tarsnap: Option -L is not permitted in mode --list-archives
Couldn't get list of existing archives, exiting.
Hint: is Tarsnap configured correctly?
Exiting unexpectedly.
```

I didn't see an option in https://www.tarsnap.com/man-tarsnap.conf.5.html.

**Comment by alexjurkiewicz** [comment]
Try adding -L to tarsnapbackupoptions in acts.conf.

**Comment by brunoqc** [comment]
It worked. Thanks!

**Comment by jepace** [comment]
The primary directory I'm tarsnapping has a space in it (which bugs me, but I can't change it).  So, I would prefer to have this work without a workaround, in some future version of acts.

**Comment by simonmichael** [comment]
I'd like to see this handled as well, because not backing up some valid data seems against the whole point of a backup tool, and creates fear and uncertainty (Do I have files/directories with spaces in their name ? What other names will acts not back up ? Will they be silently ignored, loudly reported, cause backups to fail ? Am I sure I'll remember how to handle this safely over the long term ?)

**Comment by assistcontrol** [comment]
Tarsnap handles spaces perfectly. Things with spaces get backed up just fine. The only thing that acts doesn’t support is specifying an archive root that has spaces in it.

`backuptargets=“var/data/db name with spaces”` would fail. But `backuptargets=“var/data”` would back up `/var/data/db name with spaces` with no issue.

You could:

- Use symlinks
- Make the backup target the directory _containing_ the one with spaces.

**Comment by simonmichael** [comment]
Ah, I misunderstood.  That’s less of an issue, thanks.

**Comment by simonmichael** [comment]
(That could be made clearer in the issue name.)
